### ISSUE TITLE
Lagging follower is forced to truncate its log repeatedly

### ISSUE THREAD

**Issue by madjam** [atomix/copycat#158]
I noticed this during a test run. This is a 3 node set up. One of the follower keeps resetting itself (truncate log) as it always discovers that the `globalIndex` is greater than what it is aware of. A brief look at the logic in `PassiveState::checkGlobalIndex` tells me that this should not happen on start up.

Here are some log lines. (This pattern keeps repeating)

```
2016-02-18 23:18:49,572 | DEBUG | FollowerState | 10.254.1.207/10.254.1.207:9876 - Received AppendRequest[term=1, leader=184429489, logIndex=0, logTerm=0, entries=[0], commitIndex=3288, globalIndex=3288]
2016-02-18 23:18:49,572 | DEBUG | SegmentManager | Closing segment: 1
2016-02-18 23:18:49,573 | DEBUG | SegmentManager | Created segment: Segment[id=1, version=1, index=0, length=0]
2016-02-18 23:18:49,573 | DEBUG | FollowerState | 10.254.1.207/10.254.1.207:9876 - Sent AppendResponse[status=OK, term=1, succeeded=true, logIndex=0]
2016-02-18 23:18:49,573 | DEBUG | FollowerState | 10.254.1.207/10.254.1.207:9876 - Received AppendRequest[term=1, leader=184429489, logIndex=0, logTerm=0, entries=[0], commitIndex=3292, globalIndex=3292]
2016-02-18 23:18:49,573 | DEBUG | SegmentManager | Closing segment: 1
2016-02-18 23:18:49,573 | DEBUG | SegmentManager | Created segment: Segment[id=1, version=1, index=0, length=0]
2016-02-18 23:18:49,573 | DEBUG | FollowerState | 10.254.1.207/10.254.1.207:9876 - Sent AppendResponse[status=OK, term=1, succeeded=true, logIndex=0]
2016-02-18 23:18:49,574 | DEBUG | FollowerState | 10.254.1.207/10.254.1.207:9876 - Received ConfigureRequest[term=1, leader=184429489, index=3295, members=[ServerMember[type=ACTIVE, status=AVAILABLE, serverAddress=/10.254.1.207:9876, clientAddress=/10.254.1.207:9876], ServerMember[type=ACTIVE, status=AVAILABLE, serverAddress=/10.254.1.201:9876, clientAddress=/10.254.1.201:9876], ServerMember[type=ACTIVE, status=AVAILABLE, serverAddress=/10.254.1.202:9876, clientAddress=/10.254.1.202:9876]]]
2016-02-18 23:18:49,574 | DEBUG | FollowerState | 10.254.1.207/10.254.1.207:9876 - Sent ConfigureResponse[status=OK]
2016-02-18 23:18:49,750 | DEBUG | FollowerState | 10.254.1.207/10.254.1.207:9876 - Received AppendRequest[term=1, leader=184429489, logIndex=0, logTerm=0, entries=[180], commitIndex=3294, globalIndex=3294]
2016-02-18 23:18:49,750 | DEBUG | SegmentManager | Closing segment: 1
2016-02-18 23:18:49,750 | DEBUG | SegmentManager | Created segment: Segment[id=1, version=1, index=0, length=0]
```
I'll continue looking into this more but thought I'd log an issue in case @kuujo you already know what is causing this.

**Comment by kuujo** [comment]
I do @madjam. This is something I added a while back, and I'll explain why. There may be a bug in this algorithm.

Recall from our previous discussions that `globalIndex` defines the highest index stored on all servers to allow tombstones to be compacted from the log. A tombstone has to be applied on all servers to ensure it removed state prior to being removed from the log. However, this can prevent log compaction from progressing while a server is down since we can't know whether the server is dead or alive and partitioned. 

Originally, there was no solution for `globalIndex` not being able to increase. In the event that any server was partitioned, `globalIndex` would simply stop increasing until the partition was healed. However, a while back I improved the algorithm to allow `globalIndex` to continue to increase while a server is partitioned, though it shouldn't happen this easily. 

I wrote about this part of the algorithm here:
http://atomix.io/copycat/docs/internals/#major-compaction-liveness

The idea is, in order to allow major compaction to progress while a node is partitioned, the leader tracks the availability of followers (it's ability to successfully send heartbeats to them) and commits a configuration change setting their status to UNAVAILABLE if the leader fails several heartbeats to the follower. This is done in the `LeaderAppender` (sorry I'm on my phone ATM). The leader then calculates `globalIndex` based only on `AVAILABLE` members. This allows `globalIndex` to potentially increase beyond the `lastIndex` of a partitioned follower. But once `globalIndex` increases beyond the `lastIndex` of a follower, that follower must assume that any server sending it entries could have run major compaction and compacted a tombstone from the log somewhere between the follower's `lastIndex` and the `globalIndex`. This, if a follower receives a `globalIndex` greater than its `lastIndex`,  the only safe way to recover the full state of the log is to truncate its log and begin receiving entries again from the start. Once the leader is able to send successful AppendEntries requests to the follower, its status will be reset to AVAILABLE and `globalIndex` will stop increasing until the follower is caught up.

Does that make sense? Basically, `globalIndex` should only increase beyond a follower's `lastIndex` if the leader has committed a configuration change setting the follower's status to UNAVAILABLE, and it's the follower's responsibility to recognize the increase in `globalIndex` and protect its consistency by forcing the entire log to be resent.

This *should* only happen if the follower is partitioned for a significant amount of time. There's not really any rush in increasing `globalIndex`, so we should err on the side of preventing a full snapshot of the log from having to be resent if a follower is partitioned briefly. Currently, it happens after 3 failed heartbeats.

It seems like in this case `globalIndex` is being increased improperly, forcing the follower to truncate its log and reset its state. Maybe the leader is improperly marking that follower as UNAVAILABLE.

**Comment by kuujo** [comment]
I'm going to edit this to add links to the code...

**Comment by kuujo** [comment]
Actually, there's an issue in [this condition](https://github.com/atomix/copycat/blob/master/server/src/main/java/io/atomix/copycat/server/state/PassiveState.java#L151-L154) that may be contributing to this issue. The follower is using `Log.contains` to determine whether the `globalIndex` is contained in its log, but if the `globalIndex` has been released or compacted from its log then that will return `false`. It's possible for that entry to have been excluded from replication if the leader applied and then released it and it was a non-tombstone entry. The replication algorithm is optimized to skip entries that don't need to be replicated since they no longer contribute to the state machine's state. This may be what's happening here. We should check against `lastIndex`. I'll submit a PR.

**Comment by madjam** [comment]
Thanks for the explanation @kuujo 
My only comment is that 3 failed heartbeats to mark a follower as `UNAVAILABLE` seems rather aggressive. This can easily happen during deployments or even a minor network disruption. I haven't checked but hopefully this is configurable.

Your diagnosis of the problem makes sense to me as well.

**Comment by madjam** [comment]
@kuujo: I'm still seeing this behavior with #160 Luckily it is very easy to reproduce. Let me pull up some more details.

**Comment by madjam** [comment]
> `globalIndex` will stop increasing until the follower is caught up.

Where are we doing this check? From the below log lines it looks like the `globalIndex` is advancing even before the follower is fully caught up. 

```
10.254.1.207/10.254.1.207:9876 - Received AppendRequest[term=1, leader=184429488, logIndex=0, logTerm=0, entries=[0], commitIndex=2275, globalIndex=2275]
10.254.1.207/10.254.1.207:9876 - Sent AppendResponse[status=OK, term=1, succeeded=true, logIndex=0]
10.254.1.207/10.254.1.207:9876 - Received ConfigureRequest[term=1, leader=184429488, index=2279, members=[ServerMember[type=ACTIVE, status=AVAILABLE, serverAddress=/10.254.1.207:9876, clientAddress=/10.254.1.207:9876], ServerMember[type=ACTIVE, status=AVAILABLE, serverAddress=/10.254.1.202:9876, clientAddress=/10.254.1.202:9876], ServerMember[type=ACTIVE, status=AVAILABLE, serverAddress=/10.254.1.201:9876, clientAddress=/10.254.1.201:9876]]]
10.254.1.207/10.254.1.207:9876 - Sent ConfigureResponse[status=OK]
10.254.1.207/10.254.1.207:9876 - Received AppendRequest[term=1, leader=184429488, logIndex=0, logTerm=0, entries=[178], commitIndex=2278, globalIndex=2278]
<<Follower is forced to reset>>
```

**Comment by kuujo** [comment]
Yeah I think we should make the number of heartbeats or time configurable. Like I said, making `globaIndex` progress is not at all critical in most cases. It only becomes critical if a node is down for a long enough time for the disk to fill up. So, it could maybe even be based on the log size instead of only availability. That would probably eliminate this case in most circumstances, while preserving the ability to compact logs in extreme cases. The good thing about the way this is implemented is leaders can increment `globalIndex` whenever they decide it's best, and truncating logs is only dependent on it being incremented and not any other coordination.

**Comment by kuujo** [comment]
This *should* be the case simply based on how `globalIndex` is calculated. It's likely if `globalIndex` is continuing to increase that the leader still has that follower marked as UNAVAILABLE in its configuration.

Once a follower is AVAILABLE and the leader sends an AppendRequest to that follower, if the globalIndex increased that follower should truncate its log and respond with logIndex = 0 as occurs in that log. That resets the leader's matchIndex for that follower to 0 once the response is received. With the follower's status being AVAILABLE, it will be included in the next globalIndex calculation, and with the follower's matchIndex being 0, the globalIndex calculated will be 0. The leader doesn't allow globalIndex to go back in time and so does max(0, globalIndex), resulting in the globalIndex staying the same.

This is clearly what *should* happen, but here's the problem. It seems what happened here is the follower responded while the leader's status for that follower was still UNAVAILABLE. The leader updated globalIndex without including that follower's 0 matchIndex. The configuration change resetting that follower to AVAILABLE happened after the calculation of globalIndex, so the next AppendRequest included a globalIndex that had increased and forced the follower to truncate its log again.

It doesn't seem like this should continue, though, right? Once the follower's status is set to AVAILABLE and it truncated its log a second time, the globalIndex calculated upon response of logIndex = 0 should include that follower, right?

**Comment by kuujo** [comment]
Basically, it seems like `globalIndex` is recalculated before updating the `UNAVAILABLE` follower's status to `AVAILABLE`. That probably just needs to be reorganized to make sure `logIndex=0` is included to prevent `globalIndex` from advancing. But the problem is, there's still a race condition where `globalIndex` can advance from a response from an `AVAILABLE` member while the request to the `UNAVAILABLE` member is in transit since until that follower's response is received it won't be included in calculations.

**Comment by kuujo** [comment]
In that case, we should keep in mind that `globalIndex` doesn't really even need to be recomputed on each `AppendResponse`. It could be calculated periodically to avoid these types of changes while updating an `UNAVAILABLE` follower.

**Comment by kuujo** [comment]
I wonder if `globalIndex` should just be recomputed upon a successful round of heartbeats. I think that should prevent this case.

**Comment by madjam** [comment]
So it looks like from the leader's perspective the follower's state keeps flip-flopping between `AVAILABLE` and `UNAVAILABLE`. When the leader detects the follower is responding to heartbeats, it sends a big batch of updates and the follower takes a little bit to process all those log entries causing it to miss heartbeats. The leader again marks it as `UNAVAILABLE` and lets `globalIndex` advance. The follower again detects that `globalIndex` has advanced without its acknowledgement, proceeds to truncate its logs and this pattern repeats. 

As you suggest this can be prevented if leader recomputes `globalIndex` periodically and not after every round.

**Comment by kuujo** [comment]
Gotcha. I put together a fix for this and am testing it. But that the follower is missing heartbeats may imply some tuning needs to be done either on the batch size and/or intervals/timeouts and/or how followers are set to `UNAVAILABLE`. I'll submit a few PRs for all of these and also some solution to extent the time a leader waits to increase `globalIndex`, which shouldn't happen until a pretty significant amount of time as passed.

**Comment by kuujo** [comment]
extend*

**Comment by madjam** [comment]
I have not seen this problem since we merged some of the performance improvements. I feel comfortable closing this.
