### ISSUE TITLE
MapStateMachine example on atomix.io not working

### ISSUE THREAD

**Issue by gitanuj** [atomix/copycat#168]
I'm trying to get Copycat running but sadly it's not working. I'm trying to run the example posted on Getting Started page of atomix.io. The CopycatServers successfully form a cluster and elects a leader but CopycatClient never completes any Command/Query. The client prints in the log that it is sending command, but the servers never receive it and leads to indefinite waiting at the client side.

Here's the code I'm using
https://github.com/gitanuj/lucid-db

I'm assuming that there are only 2 servers and one client (all on localhost).

**CopycatTestClient** is run with arguments "5000 5001"
1st instance of **CopycatTestServer** is run with args "5000 5001"
2nd instance of **CopycatTestServer** is run with args "5001 5000"

**Comment by kuujo** [comment]
Taking a look...

**Comment by kuujo** [comment]
@gitanuj I'm going to speculate a bit here based on what I see and then give you a few minor pointers...

First, the reason that the commands are not working may be due to serialization. `Command` and `Query` are serializable. When you run this, you'll likely see something like a `SerializationException` thrown, and here's why. By default, the Catalyst `Serializer` does *not* allow unknown classes to be serialized or deserialized. That is, it does not allow arbitrary classes to be sent between the client and server by simply serializing the class name. This is because deserializing classes in this manner is a known security risk, so Catalyst *disables* that behavior by default.

However, you *can* disable whitelisting on the client and server serializers:
```java
CopycatClient client = CopycatClient.builder(members)
  .withTransport(new NettyTransport())
  .build();
client.serializer().disableWhitelist();
```
and
```java
CopycatServer server = CopycatServer.builder(selfAddress, members)
  .withTransport(new NettyTransport())
  .withStateMachine(MapStateMachine::new)
  .withStorage(new Storage("logs/" + args[0] + System.currentTimeMillis()))
  .build();
server.serializer().disableWhitelist();
```

This will allow Catalyst to serialize *any* `Serializable` or `Externalizable` or `CatalystSerializable` object with its class name if the class has not been registered. Alternatively, without disabling whitelisting you can explicitly register the class with the serializer on both the client and server to tell Catalyst that the class is safe to serialize/deserialize:

```java
client.serializer().register(PutCommand.class);
client.serializer().register(GetQuery.class);
client.serializer().register(RemoveCommand.class);
```
and
```java

server.serializer().register(PutCommand.class);
server.serializer().register(GetQuery.class);
server.serializer().register(RemoveCommand.class);
```

This also allows Catalyst to generate a 32-bit ID based on the class name to reduce the number of bytes necessary to serialize the commands/queries.

Here's the relevant Catalyst `Serializer` documentation:
http://atomix.io/catalyst/api/latest/io/atomix/catalyst/serializer/Serializer.html#disableWhitelist--

Now for some pointers. This actually made me realize I need to update that documentation. The method that the Getting Started guide is using for log compaction is fairly advanced. Essentially, Raft writes state changes to a replicated log and applies commands to the state machine. To prevent logs from filling up the disk, Copycat implements an incremental log compaction algorithm over which the state machine has significant control, but that control comes at a price in state machines.

In the *Getting Started* guide's examples on the website, note that the code stores the `Commit` object as the values of the map. This is because the incremental log compaction algorithm *requires* that state machines hold on to the `Commit` object as long as the commit contributes to the state machine's state. In the case of a map state machine, that means a `PutCommand` commit needs to be held open until another `PutCommand` or `RemoveCommand` with the same key is committed, overriding or removing the first commit. When that happens, the first commit can be `close()d` to tell Copycat it's okay to remove that commit from the replicated log. If a `Commit` is closed while it is still stored in the state machine's `Map`, Copycat could remove that commit from the log, and in the event of a failure and replay of the log that state will be lost.

I'm sure you can see the complexity this adds to state machines, and that's why we implemented a simpler solution on top of the incremental log compaction algorithm, and I need to update the *Getting Started* documentation to reflect this approach.

The simpler - albeit less efficient - solution is snapshotting. By implementing snapshotting, the map state machine can be implemented in exactly the way you've implemented it - by simply storing the actual map keys and values in the state machine's `Map`. To implement support for snapshotting in a state machine, simply implement the `Snapshottable` interface:

```java
public class MapStateMachine extends StateMachine implements Snapshottable {
  private Map<Object, Object> map = new HashMap<>();

  @Override
  public void snapshot(SnapshotWriter writer) {
    // Serialize the map to the snapshot
    writer.writeObject(map);
  }

  @Override
  public void install(SnapshotReader reader) {
    // Read the snapshotted map
    map = reader.readObject();
  }

  public Object put(Commit<PutCommand> commit) {
    try {
      Object key = commit.operation().key();
      Object value = commit.operation().value();

      map.put(key, value);
      return value;
    } finally {
      commit.close();
    }
  }

  public Object get(Commit<GetQuery> commit) {
    try {
      Object key = commit.operation().key();
      return map.get(key);
    } finally {
      commit.close();
    }
  }

  public Object remove(Commit<RemoveCommand> commit) {
    try {
      Object key = commit.operation().key();
      return map.remove(key);
    } finally {
      commit.close();
    }
  }

}
```

For snapshottable state machines, rather than keeping track of which `Commit`s contribute to (are stored in) the state machine's state, Copycat periodically requests the full state of the state machine (the `Map`) and stores it on disk. Copycat determines how best to compact `Command`s from the log based on the state machine's interface. If the state machine implements `Snapshottable` then the `CompactionMode` of `Commands` handled by the state machine is `SNAPSHOT` unless otherwise specified, so to implement snapshotting for the map state machine you should also remove the `compaction` implementations in the commands (actually, the default is the magic `CompactionMode.DEFAULT` which is based on the state machine interface).

I will update the documentation to reflect this, and I'll implement a state machine example in the Copycat repo according to that documentation as well some time within the next couple hours.

**Comment by gitanuj** [comment]
Thanks a lot @kuujo! It works now.

However I was wondering even after setting sl4j log level to DEBUG, why didn't I see any SerializationException?

**Comment by kuujo** [comment]
That is a good question. I need to investigate this.

I've seen some issues with Java's `Executor` framework where executors tend
to catch exceptions without printing any stacktrace. Catalyst attempts to
resolve this issue and succeeds in many cases by wrapping an `Executor` in
a try-catch block that prints the stacktrace, but it still seems to miss
some exceptions thrown in the internal client/server threads. I catch them
in development by logging a message in the IntelliJ debugger for every
thrown exception, but we obviously need to figure out a way to make sure
those exceptions are always logged.
