### ISSUE TITLE
StorageLevel.MEMORY and DISK (under some conditions) cause server cannot start (Groovy lang)

### ISSUE THREAD

**Issue by brotherdetjr** [atomix/copycat#207]
Hi,

Tried your "hello world" example. When specifying the same storage directory for all server instances, they all start succesfully, I get expected message in SLF4J log, my future callback specified in thenAccept() is called, client can connect the server.

When specifying unique log dir for each instance or StorageLevel.MEMORY, the server cannot start. No complaints/warning/errors in SLF4J log or in console, client cannot connect the server.

This might be due to I write it in Groovy. Here's the gist:
https://gist.github.com/brotherdetjr/cf76b1da3e736a6026dc3d4be44ef3b1

see lines 62, 63

You see no magic there - just your example rewritten in Groovy.

Command line entries are trivial:
groovy server.groovy 5000 5001 5002
groovy server.groovy 5001 5000 5002
groovy server.groovy 5002 5000 5001

groovy client.groovy 5000 5001 5002 put hello kitty
groovy client.groovy 5000 5001 5002 get hello

Env: Windows 7
Java 1.8.0_25
Groovy 2.4.6

I will try writing this example in pure Java tomorrow :)

Regards,
Denis

**Comment by kuujo** [comment]
Thanks. Hmm.... Seeing if we can reproduce this in Java would indeed be nice. Not sure I can glean enough to figure out the problem from this. 

All of the extensive Copycat cluster tests are run on `MEMORY` storage and are periodically run on `DISK` and `MAPPED` storage: something odd must be going on to cause this.

Starting multiple servers pointing at the same log directory will result in unexpected problems in the cluster. Servers assume their log directory to be unique to themselves. It may work if you set unique names for each server, but I haven't tested it out.

Also, be sure you delete the log directory after a failed run if you're using persistent storage. The reason running multiple servers on the same log directory will make crazy things happen is because the first server will create its logs and then the second and third server will see and open those same logs. All servers will write to the same log file and make each other so crazy things.

**Comment by kuujo** [comment]
Are you able to run the client/server example? You may also want to enable `DEBUG` logging to see what the servers are saying to each other. With `DEBUG` logging you'll see every request and response. Perhaps that can be compared to the server example (which is runnable) logs.

**Comment by brotherdetjr** [comment]
Hi Kuujo,

Thanks for the reply. Will check it tomorrow.

**Comment by brotherdetjr** [comment]
Hi Kuujo,

Found the cause. I did not added "own" Address to members list.
When I did add, it started working correctly.

It's worth fixing code snippet here: http://atomix.io/copycat/docs/server/ (all the addresses are identical) and here: http://atomix.io/copycat/docs/server/#configuring-the-server (members list does not contain "own" address).

Also please don't ignore https://github.com/atomix/copycat/issues/208 :)

If there's a way for me to fix the docs (kinda pull request?), please let me know.

Regards,
Denis

**Comment by kuujo** [comment]
Actually, there's an open PR that will resolve this issue, so no need to fix it. The current API has been found to be difficult to understand for reasons like this. #209 enforces safety by providing separate methods for bootstrapping and joining a cluster. Each server's only argument is the local server address, and the configuration for bootstrapping or joining a cluster is provided separately.
