### ISSUE TITLE
why not build it for java 7?

### ISSUE THREAD

**Issue by liuinsect** [atomix/copycat#226]
hi kuujo, I know copycat is a good choice for  distribute cooperate,but  my company require java 7 when we develop 。  so  why not build it for java 7?    or has a java 7 version  being build?
thank you  for your answer .

**Comment by kuujo** [comment]
Copycat/Atomix were built for Java 8 because they're designed for use an asynchronous contexts with asynchronous APIs, and Java 8 introduced significant improvements that eased the development of asynchronous code. Sure, it could have been built for Java 7 and been compatible with Java 8, but Copycat/Atomix are forward looking, and we wanted to use some of the core asynchronous APIs available in Java 8 but not in Java 7. Furthermore, the timeline for stability for Copycat/Atomix aligned well with the timeline for adoption of Java 8. Plenty of companies large and small have already moved to Java 8.

There was a brief attempt to back port it, but Java 8 classes, packages, and features like `CompletableFuture`, `java.time`, and default methods are too deeply embedded in a sizable code base to make it practical. We would have to replace `CompletableFuture` with our own back port or use something like RxJava which has a significantly different model for asynchronous programming.

Maybe now it's time to upgrade :-)

**Comment by kuujo** [comment]
To be clear, consensus is a complex topic, and modifying virtually all of the asynchronous code in Copycat - which has been developed over years - would greatly risk introducing instability.

**Comment by liuinsect** [comment]
thank you for your answer , I hope I can modify it with  jdk 7 , I have try, and I think  upgrade the jdk is more easy, thank you for your answer again.

**Comment by kuujo** [comment]
I have tried too. I spent a week at one point attempting to back port it with RxJava and still didn't get very far. I highly recommend against this. The internals of Copycat rely on a very particular threading model that may not be properly enforced by alternative promises APIs. If the threading model is not done properly you can easily break Copycat's guarantees since it uses the order of single threads and queues to ensure operations occur in order, and that is vital to sequential consistency. If you do have to back port it, I recommend back porting `CompletableFuture` rather than trying to replace it with something else.

**Comment by kuujo** [comment]
But I still recommend upgrading JDK if possible :-)
