### ISSUE TITLE
Add .submit() method call to the CopycatServer class

### ISSUE THREAD

**Issue by ccleve** [atomix/copycat#274]
It would be nice to have a simple method directly on the CopycatServer class to apply a command as if it had come in from a remote client.

server.submit(Operation <T> operation): CompletableFuture

It appears that you have to create a CopycatClient to communicate with a server now. This entails some overhead, communication over a socket, serialization, etc.. Also, when I connected a remote client to a server there was a ton of chatter, frequent lost connections and recovery, etc.. I'd rather just handle all that in my application code. I'll send an external command to my app, my app will translate it into an Operation object and submit it to the server. Much cleaner, and I'll get closer control over the whole process.

**Comment by kuujo** [comment]
The problem with this is sessions. In order to support linearizable semantics, clients have to register and manage sessions. It's not as simple as just passing commands and queries to the state machine. Local calls to the cluster can be simulated using a client with `LocalTransport`, which is what's done in `AtomixReplica`. Create a client with `LocalTransport`, and then implement a `ServerSelectionStrategy` to force the client to only connect to the local server. Atomix is where this use case is natively supported, and it won't be supported in Copycat for the reasons above.

If you're losing connections with the client then please file a bug report with the client logs. But keep in mind that clients often intentionally disconnect and reconnect to new servers depending on their configured behavior and failures. The reason the client does all this is so that applications don't have to. If `CopycatServer` provides a `submit()` method so you can send a request to the server and have it written to the cluster, your code itself would have to handle connecting to the correct server when one of the servers is partitioned, getting a list of servers when the cluster configuration is changed, ordering and deduplicating events from the state machine, finding leaders, resending failed requests, etc, and still wouldn't benefit from linearizable semantics.
